title: @rscarson
author: rscarson

navbar-links:
  Home: "https://rscarson.github.io/"
  Projects:
    - Zarban's Grotto: "https://rscarson.github.io/zarban/"
    - Lavendeux: "https://github.com/rscarson/Lavendeux"

social-network-links:
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: rscarson
  twitter: rscarson

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  reddit: true

post_search: true
edit_page_button: true

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

baseurl: "blog" 
url: "https://rscarson.github.io/"


# Build settings
markdown: kramdown
